---
title: "강원도 코로나-19 현황"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup2, include=FALSE}
library( tidyverse )
library( readxl )
library( sf )
library( rvest )
library( readxl )
library( sf )
library( extrafont )
library( ggsflabel )
library( DT )



#font_import(pattern="KoPub")
fonts()
loadfonts(device="win")

url <- "https://www.provin.gangwon.kr/covid-19.html"
read_html( url ) -> gw_hp
gw_hp %>% html_node("h3 span") %>% html_text -> cDate
gw_hp %>% html_nodes(".txt-c") %>% html_text -> curCOVID


curCOVID[1] <- parse_number( str_extract(curCOVID[1], "확진자: ([0-9,]+)") )
curCOVID <- as.numeric( curCOVID )

gw_pop <- read_excel("./data/gw_pops_2020.xlsx")

gw_pop_covid <- cbind(gw_pop, curCOVID)

names( gw_pop_covid ) <- c("hjgg_cd", "region", "pops", "nop")

gw_pop_covid %>%
  mutate( hj_cd = substr(hjgg_cd, 1, 5)) 

gw_hj_sgg <- st_read("./data/gw_hj_sgg", "TL_SCCO_SIG", options="ENCODING=EUC-KR" )

```


## 강원도 코로나 발생현황  {.tabset}

강원도의 `r cDate` 총 확진자 수는 **`r curCOVID[1]`** 명이며, 시도별 현황은 다음과 같습니다.

### 확진자 현황 : 표
```{r echo=FALSE}
gw_pop_covid %>%
  select(2:4) %>%
  datatable( colnames = c( "시군", "인구(명)", "확진자수(명)"), 
             options = list(
  pageLength = 20, autoWidth = TRUE) ) %>% 
  formatRound(2:3, digits=0)
```


### 시군별 확진자 현황
```{r echo=FALSE}
gw_hj_sgg %>%
  left_join(gw_pop_covid %>%
              mutate( hj_cd = substr(hjgg_cd, 1, 5)) , by=c("SIG_CD" = "hj_cd")) %>%
  ggplot() +
    geom_sf( aes(fill = nop) ) +
    geom_sf_label_repel( aes(label = paste(region, "\n(", nop, "명)") ),
                  family="KoPubWorldDotum Medium", force=10) +
    labs(x="", y="") + 
    scale_fill_gradient2("확진자", low="#1E9600", mid="#FFF200", high="#FF0000", midpoint = median(gw_pop_covid$nop), na.value=NA) +
    theme_minimal() +
    theme(
      text = element_text(size = 12, family="KoPubWorldDotum Medium"),
      panel.grid = element_blank(),
      axis.text =  element_blank()
    ) +
    coord_sf()
```



### 만명당 확진자 현황 
```{r echo=FALSE}
gw_hj_sgg %>%
  left_join(gw_pop_covid %>%
              mutate( hj_cd = substr(hjgg_cd, 1, 5)) , by=c("SIG_CD" = "hj_cd")) %>%
  mutate( ppp = nop / (pops/10000) ) -> gw_cvd
  ggplot(gw_cvd) +
  geom_sf( aes(fill = ppp) ) +
  geom_sf_label_repel( aes(label = paste(region, "\n(", round(ppp,1),  "명)") ),
                       family="KoPubWorldDotum Medium", force=10) +
  labs(x="", y="") + 
  scale_fill_gradient2("만명당 확진자 수", low="#1E9600", mid="#FFF200", high="#FF0000", midpoint = median( gw_cvd$ppp ), na.value=NA) +
  theme_minimal() +
  theme(
    text = element_text(size = 12, family="KoPubWorldDotum Medium"),
    panel.grid = element_blank(),
    axis.text =  element_blank()
  ) +
  coord_sf()
```

